"""Exercise every bundled XLSX through the production ingest and renderer.

The report is intentionally generated, not hand-maintained.  It proves which
workbooks parse, validate, publish, and render every declared analytical view.
Run from the repository root::

    python scripts/audit_sample_workbooks.py
"""
from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.db import Base  # noqa: E402
from app.models import AnalyticalView  # noqa: E402
from app.services import ingest  # noqa: E402
from app.services.ingest_parser import parse_upload  # noqa: E402
from app.services.sld_renderer import render_view_svg  # noqa: E402


def _geometry_checker():
    path = ROOT / "tests" / "test_sld_geometry.py"
    spec = importlib.util.spec_from_file_location("sld_geometry_audit", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(module)
    return module.geometry_errors


GEOMETRY_ERRORS = _geometry_checker()
EXTERNAL_FINAL = Path.home() / "Downloads" / "ss_muarakarang_durikosambi_ingest.xlsx"


def audit_one(path: Path) -> dict:
    result = {"file": str(path), "kind": "backbone" if path.name.startswith("backbone_") else "subsystem"}
    with tempfile.TemporaryDirectory(prefix="mantaps-audit-") as tmp:
        engine = create_engine(f"sqlite:///{Path(tmp) / 'audit.db'}", future=True)
        Base.metadata.create_all(engine)
        Session = sessionmaker(bind=engine, autoflush=False, autocommit=False)
        with Session() as db:
            try:
                parsed = parse_upload(path.read_bytes(), path.name)
                result.update({
                    "code": parsed["subsystem"]["code"],
                    "objects": len(parsed["objects"]),
                    "connections": len(parsed["connections"]),
                    "risks": len(parsed["risks"]),
                })
                draft = ingest.build_draft(db, parsed)
                # A clean per-workbook database has no reconciliation decisions.
                # Keep this explicit so future matching changes cannot make this
                # reproducibility audit depend on seed data.
                for node in draft["nodes"]:
                    node["resolution"] = "NEW"
                    node["canonical_id"] = None
                    node["confirmed_code"] = node.get("confirmed_code") or node["external_key"]
                    node["confirmed_name"] = node.get("confirmed_name") or node["raw_label"]
                validation = ingest.validate(db, draft)
                result["validation"] = validation
                if not validation["ok"]:
                    result["ok"] = False
                    return result
                ingest.publish(
                    db, draft, parsed["subsystem"]["code"], parsed["subsystem"]["name"],
                    parsed["meta"].get("effective_date"), parsed["subsystem"].get("apb"),
                )
                views = db.query(AnalyticalView).order_by(AnalyticalView.id).all()
                result["views"] = []
                for view in views:
                    svg = render_view_svg(db, view)
                    errors = GEOMETRY_ERRORS(svg)
                    result["views"].append({
                        "view_key": view.view_key,
                        "profile": view.rule_profile,
                        "svg_bytes": len(svg.encode("utf-8")),
                        "geometry_errors": errors,
                    })
                result["ok"] = all(not v["geometry_errors"] for v in result["views"])
            except Exception as exc:  # report the failed fixture and keep auditing
                result.update(ok=False, exception=f"{type(exc).__name__}: {exc}")
        engine.dispose()
    return result


def main() -> int:
    paths = sorted((ROOT / "samples").glob("ss_*_ingest.xlsx"))
    backbone = ROOT / "samples" / "backbone_500_ingest.xlsx"
    if backbone.exists():
        paths.append(backbone)
    # Once the final workbook is checked into samples, do not audit the local
    # authoring copy a second time under the same subsystem code.
    if (EXTERNAL_FINAL.exists()
            and EXTERNAL_FINAL.name not in {p.name for p in paths}):
        paths.append(EXTERNAL_FINAL)

    rows = [audit_one(path) for path in paths]
    out_dir = ROOT / ".render_tmp" / "sample-audit"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "workbook-audit.json").write_text(
        json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    lines = [
        "# Workbook generation audit", "",
        "Generated by `python scripts/audit_sample_workbooks.py`.", "",
        "| Workbook | Scope | Objects | Connections | Risks | Views | Result |", "|---|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        failures = sum(len(v["geometry_errors"]) for v in row.get("views", []))
        detail = "PASS" if row.get("ok") else (row.get("exception") or f"FAIL ({failures} geometry errors)")
        lines.append(
            f"| `{Path(row['file']).name}` | {row['kind']} | {row.get('objects', '-')} | "
            f"{row.get('connections', '-')} | {row.get('risks', '-')} | {len(row.get('views', []))} | {detail} |"
        )
        for view in row.get("views", []):
            for error in view["geometry_errors"]:
                lines.append(f"\n- `{view['view_key']}`: {error}")
        for problem in row.get("validation", {}).get("problems", []):
            lines.append(f"\n- `{Path(row['file']).name}` validation: {problem}")
    (out_dir / "WORKBOOK_AUDIT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0 if all(row.get("ok") for row in rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
