"""Buku Kerawanan SJB 2026, Tabel 1.3 Peralatan and Tabel 1.4 Pembangkit, as-is.

These two tables of chapter 1 (Sistem 500 kV) are equipment and generation
findings -- control-centre servers, SCADA, fibre, cyber, black start, fuel
supply -- that sit on no single topology object, so they are published as the
book's own tables rather than pinned onto an SLD. A row that happens to name a
GITET or a plant is linked to it by name in the viewer ("disebut"), never
pinned.

Writes samples/system_tables_jamali.json (committed: the PDF is not in the
repo). Rows are cut by the table's own No column running 1..N, the same rule
as the subsystem tables, so a range that strays into a neighbouring table
fails here instead of publishing someone else's rows.

    python scripts/make_system_tables_json.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pdfplumber

from _kerawanan_sections import SYSTEM_TABLES
from _kerawanan_tables import PDF, _strip_chrome, clean, contingency_of

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "samples" / "system_tables_jamali.json"

# key, book section, caption as printed, the second column's own heading
TABLES = [
    ("PERALATAN", "1.6", "Tabel 1.3 Kerawanan Peralatan", "UIT / Unit"),
    ("PEMBANGKIT", "1.7", "Tabel 1.4 Kerawanan Pembangkit", "Regional"),
]


def _pages(caption: str) -> tuple[tuple[int, int], int]:
    for label, pages, n, _fixture in SYSTEM_TABLES:
        if label == caption:
            return pages, n
    raise SystemExit(f"{caption} is not in _kerawanan_sections.SYSTEM_TABLES")


TABLE_SETTINGS = {"text_x_tolerance": 1.5}

# Word's Symbol-font bullets land in the Private Use Area (U+F0B7 and kin),
# which renders as a box or nothing at all outside that font.
_PUA = re.compile("[-]")


def _cell(text: str) -> str:
    return clean(_PUA.sub("•", _strip_chrome(text)))


def table_rows(page_from: int, page_to: int, expected: int) -> list[dict]:
    """The numbered rows of ONE table, which may share its first or last page
    with a neighbour (Tabel 1.3 ends and 1.4 starts on p.72).

    A row starts where the No column holds the next number in sequence; the
    second column is not a UIT code here (UIP2B, IP/NP/IPP, JAMALI, or even
    empty), so it cannot be the signal the subsystem tables use.
    """
    runs: list[list[list[str]]] = []
    current: list[str] | None = None
    with pdfplumber.open(PDF) as pdf:
        for pno in range(page_from, page_to + 1):
            # 1.5 pt, not pdfplumber's 3: these narrow justified cells set
            # word gaps under 3 pt, which glued "khususnyapada" together
            for table in pdf.pages[pno - 1].extract_tables(TABLE_SETTINGS):
                for raw in table:
                    row = [clean(c) for c in list(raw) + [None] * (6 - len(raw))][:6]
                    # repeated column headings (row 20 itself opens "Kondisi
                    # Catudaya ...", so match the heading, not the word)
                    if row[0] == "No" or re.match(r"Kondisi\s*/", row[2]):
                        continue
                    if row[0].isdigit():
                        n = int(row[0])
                        if n == 1:
                            runs.append([])
                        if runs and n == len(runs[-1]) + 1:
                            current = row
                            runs[-1].append(current)
                            continue
                    if current:
                        for i in range(1, 6):
                            if row[i]:
                                current[i] = clean(f"{current[i]} {row[i]}")
    # the run of the right length: the page range may hold the tail of the
    # table before it (Pembangkit's first page ends Peralatan) or the head of
    # the next one
    run = next((r for r in runs if len(r) == expected), None)
    if run is None:
        raise SystemExit(f"no 1..{expected} run on p.{page_from}-{page_to}: "
                         f"{[len(r) for r in runs]}")
    return [dict(no=int(r[0]), unit=_cell(r[1]), kondisi=_cell(r[2]),
                 dampak=_cell(r[3]), mitigasi=_cell(r[4]), usulan=_cell(r[5]),
                 category=contingency_of(r[2]))
            for r in run]


def build() -> dict:
    tables = []
    for key, section, caption, unit_label in TABLES:
        (a, b), n = _pages(caption)
        tables.append({"key": key, "section": section, "caption": caption,
                       "label": caption.split("Kerawanan ", 1)[1],
                       "unit_label": unit_label, "pages": [a, b],
                       "rows": table_rows(a, b, n)})
    return {
        "_README": ("Generated by scripts/make_system_tables_json.py from Buku "
                    "Kerawanan SJB 2026 (not in the repo). Chapter 1 findings with no "
                    "topology object of their own, kept as the book prints them."),
        "scope": "JAMALI",
        "source": "Buku Kerawanan Sistem & Subsistem Jawa, Madura dan Bali Tahun 2026",
        "tables": tables,
    }


if __name__ == "__main__":
    data = build()
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    for t in data["tables"]:
        print(f"{t['caption']}: {len(t['rows'])} rows (p.{t['pages'][0]}-{t['pages'][1]})")
    print(f"-> {OUT.relative_to(ROOT)}")
